files:
  - source: /**/values/sigma_strings.xml
    translation: /%original_path%-%android_code%/%original_file_name%
  - source: /**/values/sigma_arrays.xml
    translation: /%original_path%-%android_code%/%original_file_name%
